services:
  sphraiva-mcp-web-app:
    image: ${DOCKER_REGISTRY-}mcpwebapp
    build:
      context: .
      dockerfile: src/MCP.WebApp/MCP.WebApp/Dockerfile

  sphraiva-mcp-host:
    image: ${DOCKER_REGISTRY-}sphraiva-mcp-host
    container_name: sphraiva-mcp-host
    build:
      context: .
      dockerfile: src/MCP.Host/Dockerfile
    environment:
      - MCP_SERVER=http://sphraiva-mcp-server:8080
      - OLLAMA_SERVER=http://sphraiva-ollama:11434
      - LLM_MODEL=devstral
      - QDRANT_HOST=sphraiva-qdrant
      - QDRANT_PORT=6334

  sphraiva-mcp-server:
    image: ${DOCKER_REGISTRY-}sphraiva-mcp-server
    container_name: sphraiva-mcp-server
    build:
      context: .
      dockerfile: src/MCP.Server/Dockerfile

  sphraiva-mcp-backgroundworker-filesystem:
    image: ${DOCKER_REGISTRY-}sphraiva-mcp-backgroundworker-filesystem
    container_name: sphraiva-mcp-backgroundworker-filesystem
    build:
      context: .
      dockerfile: src/MCP.BackgroundWorker.FileSystem/Dockerfile
    environment:
      - OLLAMA_SERVER=http://sphraiva-ollama:11434
      - LLM_MODEL=devstral
      - QDRANT_HOST=sphraiva-qdrant
      - QDRANT_PORT=6334

  sphraiva-ollama-model:
    image: ${DOCKER_REGISTRY-}sphraiva-ollama-mcp-ollama
    container_name: sphraiva-ollama
    build:
      context: .
      dockerfile: src/Ollama/Dockerfile
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_MODEL=devstral
      - OLLAMA_API_PORT=11434
      - OLLAMA_CONTEXT_LENGTH=20480
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  sphraiva-qdrant:
    image: qdrant/qdrant
    container_name: sphraiva-qdrant
    volumes:
      - qrdant-data:/qrdant/data
      
volumes:
  ollama-models:
  qrdant-data:

