services:
  sphraiva-mcp-web-app:
    image: ${DOCKER_REGISTRY-}mcpwebapp
    build:
      context: .
      dockerfile: src/MCP.WebApp/MCP.WebApp/Dockerfile

  sphraiva-open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: sphraiva-open-webui
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_SERVER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  sphraiva-n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: sphraiva-n8n
    environment:
      - OLLAMA_HOST=${OLLAMA_SERVER}
      - N8N_RUNNERS_ENABLED=true
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - GENERIC_TIMEZONE=Europe/Vienna
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=sphraiva-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    depends_on:
      sphraiva-postgres:
        condition: service_healthy

  sphraiva-mcp-host:
    image: ${DOCKER_REGISTRY-}sphraiva-mcp-host
    container_name: sphraiva-mcp-host
    build:
      context: .
      dockerfile: src/MCP.Host/Dockerfile
    environment:
      - MCP_SERVER=http://sphraiva-mcp-server:8080
      - OLLAMA_SERVER
      - LLM_MODEL
      - QDRANT_HOST=sphraiva-qdrant
      - QDRANT_PORT=6334

  sphraiva-mcp-server:
    image: ${DOCKER_REGISTRY-}sphraiva-mcp-server
    container_name: sphraiva-mcp-server
    build:
      context: .
      dockerfile: src/MCP.Server/Dockerfile

  sphraiva-mcp-backgroundworker-filesystem:
    image: ${DOCKER_REGISTRY-}sphraiva-mcp-backgroundworker-filesystem
    container_name: sphraiva-mcp-backgroundworker-filesystem
    build:
      context: .
      dockerfile: src/MCP.BackgroundWorker.FileSystem/Dockerfile
    environment:
      - OLLAMA_SERVER
      - LLM_MODEL
      - QDRANT_HOST=sphraiva-qdrant
      - QDRANT_PORT=6334

  sphraiva-ollama-model:
    image: ${DOCKER_REGISTRY-}sphraiva-ollama-mcp-ollama
    container_name: sphraiva-ollama
    build:
      context: .
      dockerfile: src/Ollama/Dockerfile

  sphraiva-qdrant:
    image: qdrant/qdrant
    container_name: sphraiva-qdrant

  sphraiva-postgres:
    image: postgres:latest
    container_name: sphraiva-postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

